#ifndef __ExecMsCluster_H__
#define __ExecMsCluster_H__

// External Includes
#include "ExecBase.h"
#include "spectrum.h"
#include "SpecSet.h"

// System Includes
#include <string>
#include <vector>



namespace specnets {


// Module used constants
static const char * TMP_DIRECTORY           = "./spectra/tmp";
static const char * OUT_DIRECTORY           = "./spectra/out";
static const char * MGF_DIRECTORY           = "./spectra/out/mgf";
static const char * CLUST_DIRECTORY         = "./spectra/out/clust";

static const char DIR_SEP                 = '/';
static const char DIR_SEP_OTHER           = '\\';

static const char * CLUSTER_FILENAME_PREFIX = "clusters_0_";
static const char * CLUSTERS_FILE_PREFIX    = "clusters_";
static const char * PKLBIN_FILENAME_PREFIX  = "clusters_";



/*! \brief MsCluster invoke class.

Contains methods for preparing data for MsCluster and invokes it.

 */
class ExecMsCluster : public specnets::ExecBase
{
public:
  //! \name CONSTRUCTORS
  //@{
  /*! \brief The exemplar constructor.

   Generally this constructor should not be used. It is only used by the
   module execution factory in order to create an exemplar object (without
   valid parameters) which is then used to create a real (valid) object
   using the clone() method.
   @sa clone()
   */
  ExecMsCluster(void);

  /*! \brief The default constructor

   This is the default constructor. A valid set of parameters must be
   supplied in the input parameter. The parameters can then be verified
   using the validateParams() method.
   @sa validateParams()
   @param inputParams structure containing all input parameters necessary for execution
   */
  ExecMsCluster(const ParameterList & inputParams);

  /*! \brief The default constructor

   This is the default constructor. A valid set of parameters must be
   supplied in the input parameter. The parameters can then be verified
   using the validateParams() method.
   @sa validateParams()
   @param inputParams structure containing all input parameters necessary for execution
   @param *specSet Pointer to SpecSet structure where the concateneted spectra will be returned
   @param *fileList Vector of strings where the specs_ms.mgf: list is returned
   */
  ExecMsCluster(const ParameterList & inputParams, SpecSet *specSet, std::vector<std::string> *spectrumNames);
  //@}

  //! \name DESTRUCTOR
  //@{
  virtual ~ExecMsCluster(void);
  //@}

  //! \name ACCESSORS
  //@{
  /*! \brief Creates a new module of the virtual class with the given params.

   The parameters should be sufficient for the derived class to be invoked properly.

   @return A pointer to the newly created object
   */
  virtual ExecBase * clone(const ParameterList & input_params) const;

  //@}

  //! \name MODIFIERS
  //@{
  /*! \brief Executes the module.

   In order to call this method succesfully all the necessary data for
   execution must already be loaded into memory (data members). This can
   be accomplished using the loadInputData() method.

   @return True if execution finished successfully, false otherwise.
   @sa loadInputData()
   */
  virtual bool invoke(void);

  /*! \brief Loads the input data from the files specified in the params.

   Loads all the data from files into the data members. This method is
   primarily used by the execution module to load necessary data when
   executing in a separate process..

   @return True if data was loaded successfully, false otherwise.
   @sa ExecBase(const ParameterList & input_params), saveOutputData()
   */
  virtual bool loadInputData(void);

  /*! \brief Saves all the result data to files specified in the params.

   Saves all the result data generated by the module to files specified
   by values in the params. This is used to either save the data permanantly,
   or to be loaded back in after remote execution is finished and results
   need to be merged by the merge() method.

   @param filenames A list of file names that contain the data necessary to run the module
   @return True if data was saved successfully, false otherwise.
   @sa ExecBase(const ParameterList & input_params), loadInputData(), merge()
   */
  virtual bool saveOutputData(void);

  /*! \brief Saves all the internal data into files specified in the params.

   Saves all the data required for an external process to execute the
   module. The external process would call loadInputData() to reload the
   data into the members before calling invoke(). The user passes a vector
   that will contain the names of all files necessary to run the module as
   a separate process. The first file in this list will always be the main
   parameter file.

   @param filenames A list of file names that contain the data necessary to run the module
   @return True if data was saved successfully, false otherwise.
   @sa ExecBase(const ParameterList & input_params), loadInputData()
   */
  virtual bool saveInputData(std::vector<std::string> & filenames);

  /*! \brief Loads the output data from the files specified in the params.

   Loads all the data from output files into the data members. The purpose
   of this is to ready "child" modules to be merged back together after
   being executed separately.

   @return True if data was loaded successfully, false otherwise.
   @sa ExecBase(const ParameterList & input_params), saveOutputData()
   */
  virtual bool loadOutputData(void);

    /*! \brief Splits the module into multiple "children" for parallel execution.

     Divides the work required by the module into a vector of sub-modules
     that can be executed in parallel (by the the ParallelExecution() class.

     @param numSplit Number of separate modules to split into
     @return The set of sub-modules (children) that the original module has been split into.
     An empty vector implies an error.
     @sa merge()
     */
    virtual std::vector<ExecBase *> const & split(int numSplit);

    /*! \brief Merges the child modules back into a complete result

     This method is only called when split is used for parallel execution
     and after the execution of all children has been completed. This method
     will merge the results generated by each of the child modules into
     one cohesive result as if the module had been run as a single entity.

     @return True if merge could be performed successfully, false otherwise.
     @sa split(int numSplit)
     */
    virtual bool merge(void);

  /*! \brief Performs validation of the input parameters.

   Checks the parameters structure provided in the constructor to see if they
   are sufficient and correct to invoke the module. Also sets the internal
   validity flag so that isValid() will return the correct result.

   @param error A description of the error (if any occurs)
   @return True if the parameters for the module are valid, false otherwise.
   @sa isValid()
   */
  virtual bool validateParams(std::string & error);
  //@}

protected:
  

private:
  
  // Variables to store directory listing and generated mgf files (just file names)
  vector<string> directoryListing, mgfFiles;
  

  // Combined SpecSet 
  SpecSet *m_combinedSpecSet;
  
  // File list -- used to be for spec_ms.txt
  std::vector<std::string>  *m_spectrumNames ;

  // Owner of private pointed objects
  bool  m_dataOwned;

  // Calls MsCluster
  // exeDir: base directory
  int  callMsCluster(string & exeDir);
  
  // Removes the files on a given directory
  // dir: directory where the files are
  // files: files to remove
  void removeFolderFiles(string &dir, std::vector<std::string> &files);
  
  // Removes a directory and it's files
  // folder: directory to remove
  void removeFolder(string &folder);

  //
  bool mergeInputFiles(vector<string> &outMgfDirectoryListing);

  
  //! \name NOT IMPLEMENTED
  //@{
  ExecMsCluster(const ExecBase & that);
  //@}
};

} // namespace specnets


#endif

