function newContigs = getScoreDistContigs(contigs, mainPep, pepsToAlign)
%
%  Generates a dataset for estimating the relevance of a score given (shift, aligned peptide's mass)
%
%  NOTE: assumes that the main peptide only has correct prms and no replicas (as generated by assembleC by keeping only the overlapped prms)
%

totalMassPep = contigs{mainPep,5};
positionPep = contigs{mainPep,6};

masses = unique([contigs{pepsToAlign,5}])';
masses = masses(find(masses<totalMassPep));
szMasses = size(masses,1);

newContigs = cell(size(pepsToAlign,1)*szMasses,size(contigs,2));
newContigs(1,:) = contigs(mainPep,:);

curContig = 2;
for m=1:szMasses
    curMass = masses(m);
    idx = find([contigs{pepsToAlign,5}]>=curMass);
    for i=1:size(idx,2)
        newContigs{curContig,1} = contigs{pepsToAlign(idx(i)),1};
        newContigs{curContig,2} = [];
        newContigs{curContig,3} = [contigs{pepsToAlign(idx(i)),3}(1:curMass-57,:); [[curMass-56:curMass]' zeros(57,2)] ; curMass -1 -1];
        idxPrmKeep = find([contigs{pepsToAlign(idx(i)),4}{:,1}] <= curMass-57);
        newContigs{curContig,4} = contigs{pepsToAlign(idx(i)),4}(idxPrmKeep,:);
        newContigs{curContig,5} = curMass;
        newContigs{curContig,6} = contigs{pepsToAlign(idx(i)),6};
        curContig = curContig + 1;
    end;
end;

newContigs = newContigs(1:curContig-1,:);  % return only the used positions
